thisdir = class/System.Management
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Management.dll
LIB_REFS = System System.Configuration.Install
LIB_MCS_FLAGS = /r:$(corlib)
NO_TEST = yes

include ../../build/library.make
