thisdir = class/TypeForwarders/System.ServiceModel.Primitives
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.ServiceModel.Primitives.dll
LIB_MCS_FLAGS = /r:System.ServiceModel /r:System.XML

NO_TEST = yes

include ../../../build/library.make
