thisdir = class/TypeForwarders/System.Resources.ResourceManager
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.Resources.ResourceManager.dll
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../../build/library.make
