namespace System.Windows.Serialization {
	public enum XamlNodeType {
		Attribute,
		ClrEvent,
		ConstructorParametersEnd,
		ConstructorParametersStart,
		ConstructorParameterType,
		DefAttributeKeyType,
		DefAttribute,
		DefTag,
		DocumentEnd,
		DocumentStart,
		ElementStart,
		ElementEnd,
		EndAttributes,
		KeyElementEnd,
		KeyElementStart,
		Language,
		LiteralContent,
		PIMapping,
		Property,
		PropertyArrayEnd,
		PropertyArrayStart,
		PropertyComplexEnd,
		PropertyComplexStart,
		PropertyIDictionaryEnd,
		PropertyIDictionaryStart,
		PropertyIListEnd,
		PropertyIListStart,
		PropertyWithType,
		RoutedEvent,
		Text,
		UnknownAttribute,
		UnknownTagEnd,
		UnknownTagStart
	} ;
}	
