.\" 
.\" cert2spc manual page.
.\" Copyright 2002, 2003 Motus Technologies
.\" Author:
.\"   Sebastien Pouliot (spouliot@motus.com)
.\"
.TH Mono "cert2spc"
.SH NAME
cert2spc \- Transform multiple X.509 certificates to a Software 
Publisher Certificate
.SH SYNOPSIS
.PP
.B cert2spc certificate|crl [certificate|crl ...] outputfile.spc
.SH DESCRIPTION
Combine a list of X.509 certificates or X.509 CRL (Certificate 
Revocation List) into a Software Publisher Certificate (PKCS#7
file). The SPC file is required for signing a PE file (like an
assembly) using signcode.
.SH PARAMETERS
.TP
.I "certificate"
One (or more) X.509 certificate to add (space separated).
.TP
.I "crl"
One (or more) X.509 CRL to add (space separated).
.TP
.I "output.spc"
Software Publisher Certificate to output. If the specified file 
exists it will be overwritten.
.SH AUTHOR
Written by Sebastien Pouliot
.SH COPYRIGHT
Copyright (C) 2002, 2003 Motus Technologies. 
Released under BSD license.
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-devel-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
.SH SEE ALSO
.BR makecert(1), signcode(1)


