.\" 
.\" cert-sync  manual page.
.\" Copyright 2016 Microsoft Corp
.\" Author:
.\"   Jo Shields <joshield@microsoft.com>
.\"
.TH Mono "cert-sync"
.SH NAME
cert-sync \- Mono Certificate Store Sync Tool
.SH SYNOPSIS
.PP
.B cert-sync [--quiet] [--user] filename
.SH DESCRIPTION
This tool allows you to populate a Mono certificate store, from a large 
concatenated list of certificates in PEM format (commonly provided on most 
Linux distributions).

Its use is intended to be automated at Mono install time, by distribution 
packagers, to seamlessly provide SSL support to Mono applications without 
further user interaction.
.SH OPTIONS
.TP
.I "--quiet"
Suppress verbose output
.TP
.I "--user"
Populate the per-user store in the user's home directory, instead of the 
system-wide store.
.TP
.I "filename.crt"
Path to a certificate bundle. The Mono store will have any extra entries 
removed, and new entries added, to reflect the provided file.

.SH EXAMPLES
.TP
.B cert-sync /etc/ssl/certs/ca-certificates.crt
Synchronize the machine store, from the Debian cert store location
.TP
.B cert-sync --user /etc/pki/tls/certs/ca-bundle.crt
Synchronize the user store, from the Red Hat cert store location

.SH AUTHOR
Written by Jo Shields

.SH COPYRIGHT
Copyright (C) 2016 Microsoft Corp
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
.SH SEE ALSO
.BR certmgr(1)
