.\" 
.\" chktrust manual page.
.\" Copyright 2003 Motus Technologies
.\" Copyright 2004 Novell
.\" Author:
.\"   Sebastien Pouliot (sebastien@ximian.com)
.\"
.TH Mono "chktrust"
.SH NAME
chktrust \- Check the trust of a PE executable.
.SH SYNOPSIS
.PP
.B chktrust [options] filename
.SH DESCRIPTION
Verify if an PE executable (CLR assembly, Win32 EXE or DLL) has a valid 
Authenticode(r) signature that can be traced back to a trusted certificate
authority (CA). This means that
.TP
(a) the signature is valid (i.e. file integrity) and,
.TP
(b) the code-signing certificate can be chained back to one of the 
certificates in the Trust store.
.SH OPTIONS
.TP
.I "-q", "-quiet"
Quiet mode. Limited display on console.
.TP
.I "-v", "-verbose"
Verbose mode. More details displayed on the console.
.TP
.I "-help", "-h", "-?", "/?"
Display help about this tool.
.SH KNOWN RESTRICTIONS
chktrust cannot validate Authenticode signatures on CAB files.
.SH AUTHOR
Written by Sebastien Pouliot
.SH COPYRIGHT
Copyright (C) 2003 Motus Technologies. 
Copyright (C) 2004 Novell. 
Released under BSD license.
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
.SH SEE ALSO
.BR signcode(1), makecert(1), certmgr(1), setreg(1)
