.TH "dtd2xsd" 1
.SH NAME
dtd2xsd \- XML Schema generator from XML document that contains DTD.
.SH SYNOPSIS
.B dtd2xsd
[options]
.I instance-xmlfile
.I optional-xsdfile
.SH DESCRIPTION
dtd2xsd generates an XML schema document from a document type definition (DTD).
Right now you have to specify instance XML file that references or contains
DTD. DTD itself is not readable with this tiny tool.
.PP
By default, it outputs resulting XML schema to console. If optional-xsdfile
parameter is specified, it outputs the result to the specified file.
.SH AUTHOR
Atsushi Enomoto <atsushi@ximian.com>
.SH SEE ALSO
mono(1)
