.\" 
.\" mono-symbolicate manual page.
.\" Copyright 2015 Xamarin
.\" Author:
.\"   Marcos Henrich <marcos.henrich@xamarin.com>
.\"
.TH "mono-symbolicate" 1
.SH NAME
mono-symbolicate \- Mono Symbolicate Tool
.SH SYNOPSIS
.PP
.B mono-symbolicate <msym dir> <input file>
.PP
.B mono-symbolicate store-symbols <msym dir> [<dir>]+
.SH DESCRIPTION
mono-symbolicate is a tool that converts a stack trace with <filename unknown>:0
into one with file names and line numbers.
.PP
When mono-symbolicate is called with a symbol directory and a file containing a stacktrace:
.P
.B mono-symbolicate <msym dir> <input file>
.PP
The tool writes into stdout the file contents while adding file location to stack frames when
it is possible to symbolicate with the symbols available on the symbol directory.
.PP
Managed symbols .exe/.dll can be added to the symbol directory by doing:
.P
.B mono-symbolicate store-symbols <msym dir> [<dir>]+
.SH AUTHOR
Written by Marcos Henrich
.SH COPYRIGHT
Copyright (C) 2015 Xamarin.
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-devel-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
