.\"
.\" monostyle manual page.
.\" (C) Adam Treat (manyoso@yahoo.com)
.\"
.TH monostyle 1
.SH NAME
monostyle \- Mono's C# code beautifier.
.SH SYNOPSIS
.PP
.B monostyle
-f file.cs -l <true|false> > output.cs
.SH DESCRIPTION
monostyle will parse a C# source code file and correct brace formatting
reflective of the Mono Project's coding standard. To use: invoke monostyle
by passing a C# source code file with '-f file.cs' and specify whether to
use linespacing with '-l <true|false>.  To output to a file just redirect
with '>'.
.PP
Mono's Coding Standard
.PP
* The opening brace following a namespace, class, struct, enum, property or
flow control unit should be at the end of the declaration line.
.PP
* The opening brace for a function should be on the line following the function.
.PP
* Please use white space around operators and a space between function names
and their parameters.
.SH OPTIONS
.TP
.I \-\-file
The csharp source file to parse.
.TP
.I \-\-line
Specifies wether to use line spacing.
.PP
.SH AUTHORS
Adam Treat (manyoso@yahoo.com)
.PP
.SH LICENSE
MonoStyle is released under the terms of the GNU GPL.
.PP
.SH SEE ALSO
mono(1), mint(1)
