.\" 
.\" secutil manual page.
.\" Copyright 2002, 2003 Motus Technologies
.\" Author:
.\"   Sebastien Pouliot (spouliot@motus.com)
.\"
.TH Mono "secutil"
.SH NAME
secutil \- Extract X.509 certificates and strongnames from assemblies.
.SH SYNOPSIS
.PP
.B secutil [options] filename
.SH DESCRIPTION
Extract X.509 certificates and strongnames from assemblies in a 
format that can be easily re-used in source code (C# or VB.NET syntax).
.SH OPTIONS
.TP
.I "-s assembly", "-strongname assembly"
Display strongname informations about the assembly.
.TP
.I "-x assembly", "-x509certificate assembly"
Display the X509 Authenticode certificate for the assembly.
.TP
.I "-a", "-array"
Display data in a decimal array (default).
.TP
.I "-v", "-vbmode"
Display data in a VisualBasic friendly format.
.TP
.I "-c", "-cmode"
Display data in a C/C++/C# friendly format (default).
.TP
.I "-help", "-h", "-?"
Display help about this tool.
.SH AUTHOR
Written by Sebastien Pouliot
.SH COPYRIGHT
Copyright (C) 2002, 2003 Motus Technologies. 
Released under BSD license.
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-devel-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
.SH SEE ALSO
.BR sn(1), signcode(1)
