.\" 
.\" setreg manual page.
.\" Copyright 2004 Novell
.\" Author:
.\"   Sebastien Pouliot <sebastien@ximian.com>
.\"
.TH Mono "setreg"
.SH NAME
setreg \- Change settings for public key cryptography
.SH SYNOPSIS
.PP
.B setreg [options] [feature] [true|false]
.SH DESCRIPTION
Allow to configure some optional settings for public key cryptography 
parameters used in Mono.
.SH OPTIONS
.TP
.I "-q"
Quiet mode. Limited display on console.
.TP
.I "-help", "-h", "-?", "/?"
Display help about this tool.
.SH FEATURES
.TP
.I "1"
Trust the test root certificates (both Microsoft and Mono). Depending on the 
value this will add (TRUE) or remove (FALSE) the two self-signed certificates
from the current user Trust store.
.SH AUTHOR
Written by Sebastien Pouliot
.SH COPYRIGHT
Copyright (C) 2004 Novell.
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-list for details.
.SH WEB SITE
Visit http://www.mono-project.com for details
.SH SEE ALSO
.BR chktrust(1), certmgr(1), makecert(1)
