//
// This file was generated by resx2sr tool
//

namespace System.Web.Services
{
	static partial class Res
	{
		public static string GetString (string name)
		{
			return name;
		}

		public static string GetString (string name, params object[] args)
		{
			return name;
		}
	}
}
