//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mainsoft.Web.AspnetConfig {
    
    public partial class Searcher {
        protected System.Web.UI.WebControls.GridView GridView1;
    }
}
