/* This file was automatically generated by make-map from Mono.Posix.dll */

#define Mono_Posix_OpenFlags_O_RDONLY 0
#define Mono_Posix_OpenFlags_O_WRONLY 1
#define Mono_Posix_OpenFlags_O_RDWR 2
#define Mono_Posix_OpenFlags_O_CREAT 4
#define Mono_Posix_OpenFlags_O_EXCL 8
#define Mono_Posix_OpenFlags_O_NOCTTY 16
#define Mono_Posix_OpenFlags_O_TRUNC 32
#define Mono_Posix_OpenFlags_O_APPEND 64
#define Mono_Posix_OpenFlags_O_NONBLOCK 128
#define Mono_Posix_OpenFlags_O_SYNC 256

#define Mono_Posix_FileMode_S_ISUID 2048
#define Mono_Posix_FileMode_S_ISGID 1024
#define Mono_Posix_FileMode_S_ISVTX 512
#define Mono_Posix_FileMode_S_IRUSR 256
#define Mono_Posix_FileMode_S_IWUSR 128
#define Mono_Posix_FileMode_S_IXUSR 64
#define Mono_Posix_FileMode_S_IRGRP 32
#define Mono_Posix_FileMode_S_IWGRP 16
#define Mono_Posix_FileMode_S_IXGRP 8
#define Mono_Posix_FileMode_S_IROTH 4
#define Mono_Posix_FileMode_S_IWOTH 2
#define Mono_Posix_FileMode_S_IXOTH 1

#define Mono_Posix_WaitOptions_WNOHANG 0
#define Mono_Posix_WaitOptions_WUNTRACED 1

#define Mono_Posix_AccessMode_R_OK 1
#define Mono_Posix_AccessMode_W_OK 2
#define Mono_Posix_AccessMode_X_OK 4
#define Mono_Posix_AccessMode_F_OK 8

#define Mono_Posix_Signals_SIGHUP 0
#define Mono_Posix_Signals_SIGINT 1
#define Mono_Posix_Signals_SIGQUIT 2
#define Mono_Posix_Signals_SIGILL 3
#define Mono_Posix_Signals_SIGTRAP 4
#define Mono_Posix_Signals_SIGABRT 5
#define Mono_Posix_Signals_SIGBUS 6
#define Mono_Posix_Signals_SIGFPE 7
#define Mono_Posix_Signals_SIGKILL 8
#define Mono_Posix_Signals_SIGUSR1 9
#define Mono_Posix_Signals_SIGSEGV 10
#define Mono_Posix_Signals_SIGUSR2 11
#define Mono_Posix_Signals_SIGPIPE 12
#define Mono_Posix_Signals_SIGALRM 13
#define Mono_Posix_Signals_SIGTERM 14
#define Mono_Posix_Signals_SIGCHLD 15
#define Mono_Posix_Signals_SIGCONT 16
#define Mono_Posix_Signals_SIGSTOP 17
#define Mono_Posix_Signals_SIGTSTP 18
#define Mono_Posix_Signals_SIGTTIN 19
#define Mono_Posix_Signals_SIGTTOU 20
#define Mono_Posix_Signals_SIGURG 21
#define Mono_Posix_Signals_SIGXCPU 22
#define Mono_Posix_Signals_SIGXFSZ 23
#define Mono_Posix_Signals_SIGVTALRM 24
#define Mono_Posix_Signals_SIGPROF 25
#define Mono_Posix_Signals_SIGWINCH 26
#define Mono_Posix_Signals_SIGIO 27
#define Mono_Posix_Signals_SIGSYS 28

