thisdir = tools/mdbdump
SUBDIRS =
include ../../build/rules.make

PROGRAM = mdbdump.exe

LIB_REFS = Mono.Cecil System.Xml Mono.CompilerServices.SymbolWriter
LOCAL_MCS_FLAGS =

include ../../build/executable.make
