thisdir = class/System.Web.Mobile
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Web.Mobile.dll

LIB_REFS =
LIB_MCS_FLAGS = -delaysign -keyfile:../msfinal.pub

include ../../build/library.make
