using System.Runtime.CompilerServices;

// type forwards to System.Runtime.Serialization.dll for JSON serialization classes
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.Json.DataContractJsonSerializer))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.Json.IXmlJsonReaderInitializer))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.Json.IXmlJsonWriterInitializer))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.Json.JsonReaderWriterFactory))]

// type forwards to System.ServiceModel.dll for Uri template classes
[assembly: TypeForwardedTo(typeof(System.UriTemplate))]
[assembly: TypeForwardedTo(typeof(System.UriTemplateEquivalenceComparer))]
[assembly: TypeForwardedTo(typeof(System.UriTemplateMatch))]
[assembly: TypeForwardedTo(typeof(System.UriTemplateMatchException))]
[assembly: TypeForwardedTo(typeof(System.UriTemplateTable))]

// type forwards to System.ServiceModel.dll for Syndication classes
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Atom10FeedFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Atom10FeedFormatter<>))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Atom10ItemFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Atom10ItemFormatter<>))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.AtomPub10CategoriesDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.AtomPub10ServiceDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.AtomPub10ServiceDocumentFormatter<>))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.CategoriesDocument))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.CategoriesDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.InlineCategoriesDocument))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.ReferencedCategoriesDocument))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.ResourceCollectionInfo))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Rss20FeedFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Rss20FeedFormatter<>))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Rss20ItemFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Rss20ItemFormatter<>))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.ServiceDocument))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.ServiceDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationCategory))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationContent))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationElementExtension))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationElementExtensionCollection))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationFeed))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationFeedFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationItem))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationItemFormatter))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationLink))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationPerson))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.SyndicationVersions))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.TextSyndicationContent))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.TextSyndicationContentKind))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.UrlSyndicationContent))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.Workspace))]
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Syndication.XmlSyndicationContent))]

