thisdir = class/TypeForwarders/System.Text.RegularExpressions
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.Text.RegularExpressions.dll
LIB_MCS_FLAGS = /r:System

NO_TEST = yes

include ../../../build/library.make
