thisdir = class/System.Runtime.InteropServices.RuntimeInformation
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Runtime.InteropServices.RuntimeInformation.dll
LIB_REFS = System
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../build/library.make
