//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mainsoft.Web.AspnetConfig {
    
    public partial class CreateRole {
        protected System.Web.UI.WebControls.MultiView mv;
        protected System.Web.UI.WebControls.View grid;
        protected System.Web.UI.WebControls.TextBox roleName_txb;
        protected System.Web.UI.WebControls.Button roleName_bt;
        protected System.Web.UI.WebControls.Label error_lb;
        protected System.Web.UI.WebControls.GridView Roles_gv;
        protected System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        protected System.Web.UI.WebControls.View yesno;
        protected System.Web.UI.WebControls.Image Img;
        protected System.Web.UI.WebControls.Button yes;
        protected System.Web.UI.WebControls.Button no;
    }
}
