//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mainsoft.Web.AspnetConfig {
    
    public partial class Util {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.ContentPlaceHolder SiteMapLinks;
        protected System.Web.UI.WebControls.ContentPlaceHolder Main;
        protected System.Web.UI.WebControls.Button Back;
    }
}
