thisdir = tools/compiler-tester
SUBDIRS = 
include ../../build/rules.make

PROGRAM = compiler-tester.exe
NO_INSTALL = yes

LOCAL_MCS_FLAGS = -r:System.dll -r:System.Core.dll -r:System.Xml.dll

include $(topdir)/build/executable.make
