thisdir = class/System.ComponentModel.DataAnnotations
SUBDIRS =
include ../../build/rules.make

LIBRARY = System.ComponentModel.DataAnnotations.dll
LIB_REFS = System System.Core System.Xml
KEYFILE = ../winfx.pub
LIB_MCS_FLAGS = -nowarn:414

TEST_MCS_FLAGS =
TEST_LIB_REFS = System System.Core

TXT_RESOURCE_STRINGS = ../referencesource/System.ComponentModel.DataAnnotations/System.ComponentModel.DataAnnotations.txt

include ../../build/library.make
