thisdir = class/TypeForwarders/System.Runtime.Numerics
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.Runtime.Numerics.dll
LIB_MCS_FLAGS = /r:System.Numerics

NO_TEST = yes

include ../../../build/library.make
