thisdir = class/System.ServiceModel.Activation
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.ServiceModel.Activation.dll

LIB_MCS_FLAGS = -r:System.Core.dll -r:System.dll -r:System.ServiceModel.dll

TEST_MCS_FLAGS = -r:System.dll -r:System.Core.dll

include ../../build/library.make
