// CS1548: Error during assembly signing. The specified key file does not have a private key
// Line: 0

using System.Reflection;

[assembly: AssemblyKeyFile ("cs1548.pub")]

// where cs1548.pub is generated by:
// sn -k cs1548.snk
// sn -p cs1548.snk cs1548.pub

class MyClass {

	public static void Main (string [] args)
	{
	}
}
