// cs1548: Missing private key in strongname file
// Line: 6

using System.Reflection;

[assembly: AssemblyKeyFile ("cs1548.pub")]

// where cs1548.pub is generated by:
// sn -k cs1548.snk
// sn -p cs1548.snk cs1548.pub

class MyClass {

	public static void Main (string [] args)
	{
	}
}
