NETCORE_COREFX_TEST_SUITES = \
Common.Tests \
Invariant.Tests \
Microsoft.CSharp.Tests \
Microsoft.VisualBasic.Core.Tests \
Microsoft.Win32.Primitives.Tests \
Microsoft.XmlSerializer.Generator.Tests \
System.AppContext.Tests \
System.Buffers.Tests \
System.CodeDom.Tests \
System.Collections.Concurrent.Tests \
System.Collections.Immutable.Tests \
System.Collections.NonGeneric.Tests \
System.Collections.Specialized.Tests \
System.Collections.Tests \
System.ComponentModel.Annotations.Tests \
System.ComponentModel.Composition.Registration.Tests \
System.ComponentModel.Composition.Tests \
System.ComponentModel.EventBasedAsync.Tests \
System.ComponentModel.Primitives.Tests \
System.ComponentModel.Tests \
System.ComponentModel.TypeConverter.Tests \
System.Composition.AttributeModel.Tests \
System.Composition.Convention.Tests \
System.Composition.Hosting.Tests \
System.Composition.Runtime.Tests \
System.Composition.Tests \
System.Composition.TypedParts.Tests \
System.Configuration.ConfigurationManager.Tests \
System.Console.Manual.Tests \
System.Console.Tests \
System.Data.Common.Tests \
System.Data.DataSetExtensions.Tests \
System.Data.Odbc.Tests \
System.Data.SqlClient.ManualTesting.Tests \
System.Data.SqlClient.Tests \
System.Diagnostics.Contracts.Tests \
System.Diagnostics.Debug.Tests \
System.Diagnostics.DiagnosticSource.Tests \
System.Diagnostics.FileVersionInfo.Tests \
System.Diagnostics.Process.Tests \
System.Diagnostics.StackTrace.Tests \
System.Diagnostics.TextWriterTraceListener.Tests \
System.Diagnostics.Tools.Tests \
System.Diagnostics.TraceSource.Tests \
System.Diagnostics.Tracing.Tests \
System.Drawing.Common.Tests \
System.Drawing.Primitives.Tests \
System.Dynamic.Runtime.Tests \
System.Globalization.Calendars.Tests \
System.Globalization.CalendarsWithConfigSwitch.Tests \
System.Globalization.Extensions.Tests \
System.Globalization.Tests \
System.IO.Compression.Brotli.Tests \
System.IO.Compression.Tests \
System.IO.Compression.ZipFile.Tests \
System.IO.FileSystem.DriveInfo.Tests \
System.IO.FileSystem.Primitives.Tests \
System.IO.FileSystem.Tests \
System.IO.FileSystem.Watcher.Tests \
System.IO.IsolatedStorage.Tests \
System.IO.MemoryMappedFiles.Tests \
System.IO.Packaging.Tests \
System.IO.Pipelines.Tests \
System.IO.Pipes.Tests \
System.IO.Ports.Tests \
System.IO.Tests \
System.IO.UnmanagedMemoryStream.Tests \
System.Json.Tests \
System.Linq.Expressions.Tests \
System.Linq.Parallel.Tests \
System.Linq.Queryable.Tests \
System.Linq.Tests \
System.Memory.Tests \
System.Net.Http.Functional.Tests \
System.Net.Http.Unit.Tests \
System.Net.HttpListener.Tests \
System.Net.Mail.Functional.Tests \
System.Net.Mail.Unit.Tests \
System.Net.NameResolution.Functional.Tests \
System.Net.NameResolution.Pal.Tests \
System.Net.NameResolution.Unit.Tests \
System.Net.NetworkInformation.Functional.Tests \
System.Net.Ping.Functional.Tests \
System.Net.Primitives.Functional.Tests \
System.Net.Primitives.Pal.Tests \
System.Net.Primitives.UnitTests.Tests \
System.Net.Quic.Tests \
System.Net.Requests.Tests \
System.Net.Security.Tests \
System.Net.Security.Unit.Tests \
System.Net.ServicePoint.Tests \
System.Net.Sockets.Tests \
System.Net.WebClient.Tests \
System.Net.WebHeaderCollection.Tests \
System.Net.WebProxy.Tests \
System.Net.WebSockets.Client.Tests \
System.Net.WebSockets.Tests \
System.Net.WebSockets.WebSocketProtocol.Tests \
System.Numerics.Tensors.Tests \
System.Numerics.Vectors.Tests \
System.ObjectModel.Tests \
System.Private.Uri.ExtendedFunctional.Tests \
System.Private.Uri.Functional.Tests \
System.Private.Uri.Unit.Tests \
System.Reflection.Context.Tests \
System.Reflection.CoreCLR.Tests \
System.Reflection.DispatchProxy.Tests \
System.Reflection.Emit.ILGeneration.Tests \
System.Reflection.Emit.Lightweight.Tests \
System.Reflection.Emit.Tests \
System.Reflection.Extensions.Tests \
System.Reflection.Metadata.Tests \
System.Reflection.MetadataLoadContext.Tests \
System.Reflection.Tests \
System.Reflection.TypeExtensions.CoreCLR.Tests \
System.Reflection.TypeExtensions.Tests \
System.Resources.Extensions.Tests \
System.Resources.Reader.Tests \
System.Resources.ResourceManager.Tests \
System.Resources.Writer.Tests \
System.Runtime.CompilerServices.Unsafe.Tests \
System.Runtime.CompilerServices.VisualC.Tests \
System.Runtime.Extensions.Tests \
System.Runtime.Handles.Tests \
System.Runtime.InteropServices.RuntimeInformation.Tests \
System.Runtime.InteropServices.Tests \
System.Runtime.InteropServices.WindowsRuntime.Tests \
System.Runtime.Loader.DefaultContext.Tests \
System.Runtime.Loader.RefEmitLoadContext.Tests \
System.Runtime.Loader.Tests \
System.Runtime.Numerics.Tests \
System.Runtime.Serialization.Formatters.Tests \
System.Runtime.Serialization.Json.ReflectionOnly.Tests \
System.Runtime.Serialization.Json.Tests \
System.Runtime.Serialization.Primitives.Tests \
System.Runtime.Serialization.Xml.ReflectionOnly.Tests \
System.Runtime.Serialization.Xml.Tests \
System.Runtime.Tests \
System.Security.Claims.Tests \
System.Security.Cryptography.Algorithms.Tests \
System.Security.Cryptography.Csp.Tests \
System.Security.Cryptography.Encoding.Tests \
System.Security.Cryptography.OpenSsl.Tests \
System.Security.Cryptography.Pkcs.Tests \
System.Security.Cryptography.Primitives.Tests \
System.Security.Cryptography.X509Certificates.Tests \
System.Security.Cryptography.Xml.Tests \
System.Security.Permissions.Tests \
System.Security.SecureString.Tests \
System.ServiceModel.Syndication.Tests \
System.Text.Encoding.CodePages.Tests \
System.Text.Encoding.Extensions.Tests \
System.Text.Encoding.Tests \
System.Text.Encodings.Web.Tests \
System.Text.Json.Tests \
System.Text.RegularExpressions.Tests \
System.Threading.Channels.Tests \
System.Threading.Overlapped.Tests \
System.Threading.Tasks.Dataflow.Tests \
System.Threading.Tasks.Extensions.Tests \
System.Threading.Tasks.Parallel.Tests \
System.Threading.Tasks.Tests \
System.Threading.Tests \
System.Threading.Thread.Tests \
System.Threading.ThreadPool.Tests \
System.Threading.Timer.Tests \
System.Transactions.Local.Tests \
System.ValueTuple.Tests \
System.Web.HttpUtility.Tests \
System.Xml.Linq.Axes.Tests \
System.Xml.Linq.Events.Tests \
System.Xml.Linq.Misc.Tests \
System.Xml.Linq.Properties.Tests \
System.Xml.Linq.SDMSample.Tests \
System.Xml.Linq.Streaming.Tests \
System.Xml.Linq.TreeManipulation.Tests \
System.Xml.Linq.xNodeBuilder.Tests \
System.Xml.Linq.xNodeReader.Tests \
System.Xml.Misc.Tests \
System.Xml.RW.CharCheckingReader.Tests \
System.Xml.RW.CustomReader.Tests \
System.Xml.RW.FactoryReader.Tests \
System.Xml.RW.NameTable.Tests \
System.Xml.RW.ReaderSettings.Tests \
System.Xml.RW.RwFactory.Tests \
System.Xml.RW.SubtreeReader.Tests \
System.Xml.RW.WrappedReader.Tests \
System.Xml.RW.XmlConvert.Tests \
System.Xml.RW.XmlReader.ReadContentAs.Tests \
System.Xml.RW.XmlReader.Tests \
System.Xml.RW.XmlSystemPathResolver.Tests \
System.Xml.RW.XmlWriter.Tests \
System.Xml.RW.XmlWriterApi.Tests \
System.Xml.Schema.Extensions.Tests \
System.Xml.XPath.Tests \
System.Xml.XPath.XDocument.Tests \
System.Xml.XPath.XmlDocument.Tests \
System.Xml.XmlDocument.Tests \
System.Xml.XmlNodeReader.Tests \
System.Xml.XmlResolver.Tests \
System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests \
System.Xml.XmlSchemaSet.Tests \
System.Xml.XmlSerializer.ReflectionOnly.Tests \
System.Xml.XmlSerializer.Tests \
System.Xml.Xsl.XslCompiledTransformApi.Tests \
System.Xml.Xsl.XslTransformApi.Tests \
XsltCompiler.Tests \
