thisdir = tools/ictool
SUBDIRS =
include ../../build/rules.make

LOCAL_MCS_FLAGS =
LIB_REFS = System.Xml

PROGRAM = ictool.exe
EXTRA_DISTFILES = ictool-config.xml

include ../../build/executable.make
