thisdir = class/TypeForwarders/System.Globalization
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.Globalization.dll
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../../build/library.make
