//
// DueDate.cs
//
// Author:
//   Chris J Breisch (cjbreisch@altavista.net) (auto-generated by ClassGenerator)
//
// (C) 2002 Chris J Breisch
//
namespace Microsoft.VisualBasic {
	public enum DueDate : int {
		EndOfPeriod = 0,
		BegOfPeriod = 1
	};
}
