//
// Globals.cs
//
// Author:
//   Chris J Breisch (cjbreisch@altavista.net) (auto-generated by ClassGenerator)
//
// (C) 2002 Chris J Breisch
//
namespace Microsoft.VisualBasic {
	[Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute] 
	[System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Auto)] 
	sealed public class Globals {
		// Declarations
		// Constructors
		// Properties
		public static System.String ScriptEngine { get {return "";} }
		public static System.Int32 ScriptEngineMajorVersion { get {return 0;} }
		public static System.Int32 ScriptEngineMinorVersion { get {return 0;} }
		public static System.Int32 ScriptEngineBuildVersion { get {return 0;} }
		// Methods
		// Events
	};
}
