//
// Utils.cs
//
// Author:
//   Chris J Breisch (cjbreisch@altavista.net) (auto-generated by ClassGenerator)
//
// (C) 2002 Chris J Breisch
//
namespace Microsoft.VisualBasic.CompilerServices {
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)] 
	[Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute] 
	[System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Auto)] 
	sealed public class Utils {
		// Declarations
		// Constructors
		// Properties
		// Methods
		public static void ThrowException (System.Int32 hr) { }
		public static System.Object SetCultureInfo (System.Globalization.CultureInfo Culture) { return null;}
		public static System.Array CopyArray (System.Array arySrc, System.Array aryDest) { return null;}
		public static System.String MethodToString (System.Reflection.MethodBase Method) { return "";}
		// Events
	};
}
