//------------------------------------------------------------------------------
// <copyright file="DefaultMembershipAdapter.cs" company="Microsoft">
//    Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------

namespace System.Web.Security {
    using System;
    
    internal class DefaultMembershipAdapter : IMembershipAdapter {
        public DefaultMembershipAdapter() {
        }

        public MembershipProviderCollection Providers {
            get { throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported); }
        }

        public int UserIsOnlineTimeWindow {
            get { throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported); }
        }

        public bool IsDecryptionKeyAutogenerated {
            get { throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported); }
        }

        public bool UsingCustomEncryption {
            get { throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported); }
        }

        public byte[] EncryptOrDecryptData(bool encrypt, byte[] buffer, bool useLegacyMode) {
            throw new PlatformNotSupportedException(ApplicationServicesStrings.Platform_not_supported);
        }
    }
}
