
# Android

ANDROID_PLATFORM_VERSION_armeabi?=9
ANDROID_PLATFORM_VERSION_armeabi-v7a?=9
ANDROID_PLATFORM_VERSION_arm64-v8a?=21
ANDROID_PLATFORM_VERSION_x86?=9
ANDROID_PLATFORM_VERSION_x86_64?=21

# iOS

## Xcode needs to be installed in /Applications/$(XCODE_VERSION).app
XCODE_VERSION?=Xcode91

MACOS_VERSION?=10.13
MACOS_VERSION_MIN?=10.7

IOS_VERSION?=11.1
IOS_VERSION_MIN?=6.0

TVOS_VERSION?=11.1
TVOS_VERSION_MIN?=9.0

WATCHOS_VERSION?=4.1
WATCHOS_VERSION_MIN?=2.0

# WebAssembly
