thisdir = class/TypeForwarders/System.ComponentModel.Annotations
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.ComponentModel.Annotations.dll
LIB_MCS_FLAGS = /r:System.ComponentModel.DataAnnotations

NO_TEST = yes

include ../../../build/library.make
