thisdir = class/Facades/System.Linq.Queryable
SUBDIRS = 
include ../../../build/rules.make

LIBRARY_SUBDIR = Facades
LIBRARY_INSTALL_DIR = $(mono_libdir)/mono/$(FRAMEWORK_VERSION)/Facades

LIBRARY = System.Linq.Queryable.dll
LIB_MCS_FLAGS = /r:System.Core /r:System

PLATFORM_DEBUG_FLAGS =

NO_TEST = yes

include ../../../build/library.make
