thisdir = class/TypeForwarders/System.Xml.XmlSerializer
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.Xml.XmlSerializer.dll
LIB_MCS_FLAGS = /r:System.Xml

NO_TEST = yes

include ../../../build/library.make
