thisdir = docs
SUBDIRS = 
include ../build/rules.make

DISTFILES = clr-abi.txt compiler.txt control-flow-analysis.txt order.txt new-anonymous-design.txt

all-local install-local clean-local test-local run-test-local run-test-ondotnet-local uninstall-local:

dist-local: dist-default
