thisdir = class/System.Web.Abstractions
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Web.Abstractions.dll
LIB_REFS = System System.Core System.Web
KEYFILE = ../winfx.pub
LIB_MCS_FLAGS =

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

EXTRA_DISTFILES =

include ../../build/library.make
