thisdir = class/System.Private.Corlib
SUBDIRS =
include ../../build/rules.make

LIBRARY = System.Private.Corlib.dll
LIB_REFS =
EXTRA_DIST_FILES =

LIB_MCS_FLAGS =
DEFAULT_REFERENCES = 

include ../../build/library.make
