trigger:
  batch: true
  branches:
    include:
    - master
    - 20*-*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  batch: true
  branches:
    include:
    - master
    - 20*-*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

jobs:
#
# Basic build
#
- template: /scripts/ci/azdo/platform-matrix.yml
  parameters:
    jobTemplate: /scripts/ci/azdo/global-build-job.yml
    platforms:
    - windows_x86
    - OSX_x64
    - Linux_x64
    jobParameters:
      nameSuffix: Standard

#
# MCS-only build
#
- template: /scripts/ci/azdo/platform-matrix.yml
  parameters:
    jobTemplate: /scripts/ci/azdo/global-build-job.yml
    platforms:
    - Linux_x64
    jobParameters:
      nameSuffix: MCS
      extraCITags: mcs-compiler
