variables:
- ${{ if ne(variables['System.TeamProject'], 'public') }}:
  - group: DotNet-VSTS-Bot
  - group: DotNet-Blob-Feed
- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  # Variables used to publish packages to blob feed
  - name: dotnetFeedUrl
    value: https://dotnetfeed.blob.core.windows.net/mono-mono/index.json
  # Variables used by arcade to gather asset manifests
  - name: _DotNetPublishToBlobFeed
    value: true

jobs:
- job: Build
  strategy:
    matrix:
      Linux x64:
        poolname: Hosted Ubuntu 1604
        sed: sed
      OSX x64:
        poolname: Hosted macOS
        sed: gsed
  pool:
    name: $(poolname)
  steps:
  - script: |  
      brew install autoconf automake libtool gnu-sed
    displayName: 'Prepare OSX dependencies'
    condition: eq(variables['poolname'], 'Hosted macOS')

  - script: |  
      sudo apt update
      sudo apt -y install nuget build-essential libtool libtool-bin cmake gettext dotnet-sdk-2.2
    displayName: 'Prepare Linux dependencies'
    condition: eq(variables['poolname'], 'Hosted Ubuntu 1604')
  
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - script: |
        ${sed} -i "s#git://github.com/#https://dn-bot:${dncengPat}@dev.azure.com/dnceng/internal/_git/#; s#\.git\$##; s#\(url = .*\)/\(.*\)#\1-\2#" .gitmodules
      env:
        dncengPat: $(dn-bot-dotnet-build-rw-code-rw)
        sed: $(sed)
      displayName: 'Rewrite .gitmodules'

  - script: |
      ./autogen.sh --with-core=only
      make
      make -C netcore nupkg
    displayName: 'Build'
  
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    - script: |
        ./eng/common/build.sh /p:DotNetPublishToBlobFeed=true --ci --restore --projects $(Build.Repository.LocalPath)/eng/empty.proj
      displayName: 'restore Arcade stuff'
    - script: |
        dotnet msbuild eng/publishwitharcade.proj /p:AzureFeedUrl=$(dotnetfeedUrl) /p:AzureAccountKey=${dotnetFeedPat}
      env:
        dotnetFeedPat: $(dotnetfeed-storage-access-key-1)
      displayName: 'publish with Arcade'
    - task: CopyFiles@2
      displayName: Gather Asset Manifests
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/log/Debug/AssetManifest'
        TargetFolder: '$(Build.StagingDirectory)/AssetManifests'
      continueOnError: false
      condition: and(succeeded(), eq(variables['_DotNetPublishToBlobFeed'], 'true'))
    - task: PublishBuildArtifacts@1
      displayName: Push Asset Manifests
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)/AssetManifests'
        PublishLocation: Container
        ArtifactName: AssetManifests
      continueOnError: false
      condition: and(succeeded(), eq(variables['_DotNetPublishToBlobFeed'], 'true'))

- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/phases/publish-build-assets.yml
    parameters:
      dependsOn:
        - Build
      queue:
        name: Hosted VS2017
