using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.MSInternal", "CA905:SystemAndMicrosoftNamespacesRequireApproval", Scope="namespace", Target="System.Runtime.InteropServices.ComTypes")] 

[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.cfFormat")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.lindex")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.ptd")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.tymed")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.dwAspect")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.pUnkForRelease")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.unionmember")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.tymed")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.formatetc")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.advSink")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.advf")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.connection")]

[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope="type", Target="System.Runtime.InteropServices.ComTypes.DVASPECT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope="type", Target="System.Runtime.InteropServices.ComTypes.ADVF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope="type", Target="System.Runtime.InteropServices.ComTypes.TYMED")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope="type", Target="System.Runtime.InteropServices.ComTypes.TYMED")]

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IEnumSTATDATA.Next(System.Int32,System.Runtime.InteropServices.ComTypes.STATDATA[],System.Int32[]):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IEnumSTATDATA.Next(System.Int32,System.Runtime.InteropServices.ComTypes.STATDATA[],System.Int32[]):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IDataObject.DAdvise(System.Runtime.InteropServices.ComTypes.FORMATETC&,System.Runtime.InteropServices.ComTypes.ADVF,System.Runtime.InteropServices.ComTypes.IAdviseSink,System.Int32&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IDataObject.DAdvise(System.Runtime.InteropServices.ComTypes.FORMATETC&,System.Runtime.InteropServices.ComTypes.ADVF,System.Runtime.InteropServices.ComTypes.IAdviseSink,System.Int32&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IDataObject.DAdvise(System.Runtime.InteropServices.ComTypes.FORMATETC&,System.Runtime.InteropServices.ComTypes.ADVF,System.Runtime.InteropServices.ComTypes.IAdviseSink,System.Int32&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IDataObject.DUnadvise(System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IEnumFORMATETC.Next(System.Int32,System.Runtime.InteropServices.ComTypes.FORMATETC[],System.Int32[]):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IEnumFORMATETC.Next(System.Int32,System.Runtime.InteropServices.ComTypes.FORMATETC[],System.Int32[]):System.Int32")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.lindex")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.ptd")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.tymed")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.dwAspect")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.pUnkForRelease")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.unionmember")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.tymed")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.IAdviseSink.OnDataChange(System.Runtime.InteropServices.ComTypes.FORMATETC&,System.Runtime.InteropServices.ComTypes.STGMEDIUM&):System.Void")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.formatetc")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STATDATA.advf")]

[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_THUMBNAIL")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_DOCPRINT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_CONTENT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_ICON")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_DATAONSTOP")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_NODATA")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_FORCEBUILTIN")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_PRIMEFIRST")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_ONLYONCE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_NOHANDLER")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_ONSAVE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DATADIR.DATADIR_GET")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DATADIR.DATADIR_SET")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ISTORAGE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_FILE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_HGLOBAL")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ENHMF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_MFPICT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_GDI")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ISTREAM")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_NULL")]

// Cannot change names - breaking change.
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.DVASPECT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_THUMBNAIL")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_DOCPRINT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_CONTENT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DVASPECT.DVASPECT_ICON")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.IEnumSTATDATA")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.IEnumFORMATETC")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.ADVF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_DATAONSTOP")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_NODATA")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_FORCEBUILTIN")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_PRIMEFIRST")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVF_ONLYONCE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_NOHANDLER")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.ADVF.ADVFCACHE_ONSAVE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.DATADIR")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope="type", Target="System.Runtime.InteropServices.ComTypes.DATADIR")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DATADIR.DATADIR_GET")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.DATADIR.DATADIR_SET")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.FORMATETC")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.TYMED")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ISTORAGE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_FILE")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_HGLOBAL")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ENHMF")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_MFPICT")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_NULL")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_GDI")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="member", Target="System.Runtime.InteropServices.ComTypes.TYMED.TYMED_ISTREAM")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1705:LongAcronymsShouldBePascalCased", Scope="type", Target="System.Runtime.InteropServices.ComTypes.STATDATA")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.cfFormat")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.dwAspect")]

// struct fields are public and can be used individually for comparisons.   
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope="type", Target="System.Runtime.InteropServices.ComTypes.FORMATETC")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope="type", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope="type", Target="System.Runtime.InteropServices.ComTypes.STATDATA")]

// all instances are ok.
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.TypeDescriptor.CreateInstance(System.IServiceProvider,System.Type,System.Type[],System.Object[]):System.Object")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.TypeDescriptor+ComNativeDescriptionProvider.GetTypeDescriptor(System.Type,System.Object):System.ComponentModel.ICustomTypeDescriptor")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.TypeDescriptor+TypeDescriptionNode.GetTypeDescriptor(System.Type,System.Object):System.ComponentModel.ICustomTypeDescriptor")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.TypeDescriptor+TypeDescriptionNode.CreateInstance(System.IServiceProvider,System.Type,System.Type[],System.Object[]):System.Object")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.PropertyDescriptorCollection.System.Collections.IDictionary.Add(System.Object,System.Object):System.Void")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.PropertyDescriptorCollection.System.Collections.IList.set_Item(System.Int32,System.Object):System.Void")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope="member", Target="System.ComponentModel.PropertyDescriptorCollection.System.Collections.IDictionary.set_Item(System.Object,System.Object):System.Void")]

// CONSIDER: In future releases we may want to provide a strongly typed implementation of IList.
[assembly: SuppressMessage("Microsoft.Design", "CA1039:ListsAreStronglyTyped", Scope="type", Target="System.ComponentModel.Design.DesignerOptionService+DesignerOptionCollection")]
[assembly: SuppressMessage("Microsoft.Design", "CA1039:ListsAreStronglyTyped", Scope="type", Target="System.ComponentModel.ListSortDescriptionCollection")]

// Would be a breaking change.
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope="type", Target="System.ComponentModel.Design.DesignerOptionService+DesignerOptionCollection")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope="type", Target="System.ComponentModel.TypeConverter+SimplePropertyDescriptor")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope="type", Target="System.ComponentModel.TypeConverter+StandardValuesCollection")]
[assembly: SuppressMessage("Microsoft.Security", "CA2111:PointersShouldNotBeVisible", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.ptd")]
[assembly: SuppressMessage("Microsoft.Security", "CA2111:PointersShouldNotBeVisible", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.unionmember")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.Design.IRootDesigner.SupportedTechnologies")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.Design.ServiceContainer.DefaultServices")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.MemberDescriptor.AttributeArray")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.PropertyTabAttribute.TabScopes")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.PropertyTabAttribute.TabClasses")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope="member", Target="System.ComponentModel.PropertyTabAttribute.TabClassNames")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.ComponentModel.Design.IMenuCommandService.FindCommand(System.ComponentModel.Design.CommandID):System.ComponentModel.Design.MenuCommand")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.ComponentModel.Design.IMenuCommandService.GlobalInvoke(System.ComponentModel.Design.CommandID):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.ComponentModel.Design.IMenuCommandService.ShowContextMenu(System.ComponentModel.Design.CommandID,System.Int32,System.Int32):System.Void")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="type", Target="System.ComponentModel.Design.CommandID")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.ComponentModel.Design.CommandID.ID")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", Scope="member", Target="System.ComponentModel.Design.MenuCommand.CommandID")]

// Rules in error. - classes don't have any security demands (including base classes and interfaces).
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope="member", Target="System.Configuration.ApplicationSettingsBase.OnSettingChanging(System.Object,System.Configuration.SettingChangingEventArgs):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope="member", Target="System.Configuration.ApplicationSettingsBase.OnSettingsLoaded(System.Object,System.Configuration.SettingsLoadedEventArgs):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope="member", Target="System.Configuration.ApplicationSettingsBase.OnSettingsSaving(System.Object,System.ComponentModel.CancelEventArgs):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2109:ReviewVisibleEventHandlers", Scope="member", Target="System.Configuration.ApplicationSettingsBase.OnPropertyChanged(System.Object,System.ComponentModel.PropertyChangedEventArgs):System.Void")]

// These are Win32, in 64-bit plats the upper half is not used.
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.NativeMethods.RegOpenKeyEx(System.Runtime.InteropServices.HandleRef,System.String,System.IntPtr,System.Int32,System.IntPtr&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.NativeMethods.SetThreadAffinityMask(System.Runtime.InteropServices.HandleRef,System.Runtime.InteropServices.HandleRef):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.DispatchMessage(Microsoft.Win32.NativeMethods+MSG&):System.Int32")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.SetWindowLong(System.Runtime.InteropServices.HandleRef,System.Int32,System.Runtime.InteropServices.HandleRef):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.SetWindowLong(System.Runtime.InteropServices.HandleRef,System.Int32,System.Runtime.InteropServices.HandleRef):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.UnregisterClass(System.String,System.Runtime.InteropServices.HandleRef):System.Int16")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.MsgWaitForMultipleObjects(System.Int32,System.Int32,System.Boolean,System.Int32,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1901:PInvokeDeclarationsShouldBePortable", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.GetModuleFileName(System.Int32,System.Text.StringBuilder,System.Int32):System.Int32")]

// These are safe - no threat on Win9x
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.CreateNamedPipe(System.String,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,Microsoft.Win32.NativeMethods+SECURITY_ATTRIBUTES):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.LookupPrivilegeValue(System.String,System.String,Microsoft.Win32.NativeMethods+LUID&):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.GetRequestedRuntimeInfo(System.String,System.String,System.String,System.UInt32,System.UInt32,System.Text.StringBuilder,System.Int32,System.UInt32&,System.Text.StringBuilder,System.Int32,System.UInt32&):System.UInt32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.LogonUser(System.String,System.String,System.String,System.Int32,System.Int32,System.IntPtr&):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.CreateProcessWithLogonW(System.String,System.String,System.IntPtr,Microsoft.Win32.NativeMethods+LogonFlags,System.String,System.Text.StringBuilder,System.Int32,System.IntPtr,System.String,Microsoft.Win32.NativeMethods+STARTUPINFO,Microsoft.Win32.SafeNativeMethods+PROCESS_INFORMATION):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.GetModuleFileNameEx(System.Runtime.InteropServices.HandleRef,System.Runtime.InteropServices.HandleRef,System.Text.StringBuilder,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.GetModuleBaseName(System.Runtime.InteropServices.HandleRef,System.Runtime.InteropServices.HandleRef,System.Text.StringBuilder,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.NativeMethods.GetModuleHandle(System.String):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.SafeNativeMethods.GetComputerName(System.Text.StringBuilder,System.Int32[]):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.SafeNativeMethods.MessageBox(System.Runtime.InteropServices.HandleRef,System.String,System.String,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.SafeNativeMethods.OutputDebugString(System.String):System.Void")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.VerLanguageName(System.Int32,System.Text.StringBuilder,System.Int32):System.Int32")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.GetProcAddress(System.Runtime.InteropServices.HandleRef,System.String):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.GetModuleHandle(System.String):System.IntPtr")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.VerQueryValue(System.Runtime.InteropServices.HandleRef,System.String,System.IntPtr&,System.Int32&):System.Boolean")]
[assembly: SuppressMessage("Microsoft.Security", "CA2101:SpecifyMarshalingForPInvokeStringArguments", Scope="member", Target="Microsoft.Win32.UnsafeNativeMethods.CreateFile(System.String,System.Int32,System.Int32,System.IntPtr,System.Int32,System.Int32,System.IntPtr):Microsoft.Win32.SafeHandles.SafeFileHandle")]


// SafeHandles.
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Runtime.InteropServices.ComTypes.FORMATETC.ptd")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="System.Runtime.InteropServices.ComTypes.STGMEDIUM.unionmember")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.hbrBackground")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.lpszMenuName")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.hIcon")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.hInstance")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.lpszClassName")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.lpfnWndProc")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS_I.hCursor")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS.hbrBackground")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS.hIcon")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS.hInstance")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WNDCLASS.hCursor")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.TimerElapsedEventArgs.timerId")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.hInstApp")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpDirectory")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.hIcon")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpClass")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpParameters")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.hkeyClass")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpIDList")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.hwnd")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpFile")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.lpVerb")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+ShellExecuteInfo.hProcess")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods.INVALID_HANDLE_VALUE")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods.NullHandleRef")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods.HKEY_LOCAL_MACHINE")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods.InvalidIntPtr")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtProcessBasicInfo.InheritedFromUniqueProcessId")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtProcessBasicInfo.UniqueProcessId")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtProcessBasicInfo.AffinityMask")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtProcessBasicInfo.PebBaseAddress")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WinModuleEntry.modBaseAddr")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WinModuleEntry.hModule")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtModuleInfo.BaseOfDll")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+NtModuleInfo.EntryPoint")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+SECURITY_ATTRIBUTES.lpSecurityDescriptor")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+MSG.lParam")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+MSG.wParam")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+MSG.hwnd")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.lpReserved2")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.lpReserved")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.lpDesktop")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.lpTitle")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.hStdError")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.hStdOutput")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+STARTUPINFO.hStdInput")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.SafeNativeMethods+PROCESS_INFORMATION.hThread")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.SafeNativeMethods+PROCESS_INFORMATION.hProcess")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope="member", Target="Microsoft.Win32.NativeMethods+WinProcessEntry.th32DefaultHeapID")]


