thisdir = class/System.Data.Linq
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Data.Linq.dll
LIB_REFS = System System.Core System.Data System.Transactions System.Xml
KEYFILE = ../ecma.pub
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../build/library.make
