thisdir = class/I18N/Common
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = I18N.dll
LIBRARY_USE_INTERMEDIATE_FILE = yes
LOCAL_MCS_FLAGS = /r:$(corlib) /unsafe /define:DISABLE_UNSAFE
NO_TEST = yes

include ../../../build/library.make
