thisdir = class/TypeForwarders/System.Runtime
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.Runtime.dll
LIB_MCS_FLAGS = /r:System /r:System.Core /r:System.ComponentModel.Composition

NO_TEST = yes

include ../../../build/library.make
