thisdir = class/System.EnterpriseServices
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.EnterpriseServices.dll
LIB_REFS = System.Transactions
KEYFILE = ../msfinal.pub
LIB_MCS_FLAGS = /nowarn:0168 /nowarn:0162
NO_TEST = yes

include ../../build/library.make
