#!/bin/sh

for i in a-*.cs; do
        n=`basename $i .cs`
	if mono --debug mcs.exe -unsafe $i >& $n.log; then
	    if mono --debug `basename $i .cs`.exe >& $n.run; then
	    	echo "  Test passes: $i"
	    else
		echo "   Test fails: $i"
	    fi
	else
	        echo "Compile Fails: $i"
        fi
done
