//
// This file was generated by resx2sr tool
//

partial class SR
{
	public const string ArgumentException_ExtraCharacters = "Extra characters in JSON input.";
	public const string ArgumentException_IncompleteInput = "Incomplete JSON input.";
	public const string ArgumentException_UnexpectedCharacter = "Unexpected character '{0}'.";
	public const string ArgumentException_ArrayMustEndWithBracket = "JSON array must end with ']'.";
	public const string ArgumentException_LeadingZeros = "Leading zeros are not allowed.";
	public const string ArgumentException_NoDigitFound = "Invalid JSON numeric literal; no digit found.";
	public const string ArgumentException_ExtraDot = "Invalid JSON numeric literal; extra dot.";
	public const string ArgumentException_IncompleteExponent = "Invalid JSON numeric literal; incomplete exponent.";
	public const string ArgumentException_InvalidLiteralFormat = "Invalid JSON string literal format.";
	public const string ArgumentException_StringNotClosed = "JSON string is not closed.";
	public const string ArgumentException_IncompleteEscapeSequence = "Invalid JSON string literal; incomplete escape sequence.";
	public const string ArgumentException_IncompleteEscapeLiteral = "Incomplete unicode character escape literal.";
	public const string ArgumentException_UnexpectedEscapeCharacter = "Invalid JSON string literal; unexpected escape character.";
	public const string ArgumentException_ExpectedXButGotY = "Expected '{0}', got '{1}'.";
	public const string ArgumentException_ExpectedXDiferedAtY = "Expected '{0}', differed at {1}.";
	public const string ArgumentException_MessageAt = "{0} At line {1}, column {2}.";
	public const string NotImplemented_GetFormattedString = "GetFormattedString from value type {0}.";
}
