thisdir = tools/installutil
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS = -r:System.Configuration.Install.dll -r:System.dll

PROGRAM = installutil.exe

include ../../build/executable.make
