MEMDOM_TYPE_START(MonoImage)
MEMDOM_FIELD(MonoImage, mempool, MEMPOOL)
MEMDOM_FIELD(MonoImage, method_cache, G_HASHTABLE)
MEMDOM_TYPE_END()

MEMDOM_TYPE_START(MonoDomain)
MEMDOM_FIELD(MonoDomain, mp, MEMPOOL)
MEMDOM_FIELD(MonoDomain, env, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, ldstr_table, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, type_hash, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, refobject_hash, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, type_init_exception_hash, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, delegate_hash_table, MONO_HASHTABLE)
MEMDOM_FIELD(MonoDomain, proxy_vtable_hash, G_HASHTABLE)
MEMDOM_TYPE_END()

MEMDOM_TYPE_START(MonoImageSet)
MEMDOM_FIELD(MonoImageSet, gclass_cache, G_HASHTABLE)
MEMDOM_FIELD(MonoImageSet, ginst_cache, G_HASHTABLE)
MEMDOM_FIELD(MonoImageSet, gmethod_cache, G_HASHTABLE)
MEMDOM_FIELD(MonoImageSet, gsignature_cache, G_HASHTABLE)
MEMDOM_FIELD(MonoImageSet, mempool, MEMPOOL)
MEMDOM_TYPE_END()