thisdir = tools/wsdl
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS =
LIB_REFS = System.Xml System.Web.Services System

PROGRAM = wsdl.exe

CLEAN_FILES = wsdl.exe wsdl2.exe *.mdb

include ../../build/executable.make

