thisdir = class/System.Workflow.ComponentModel
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Workflow.ComponentModel.dll

LIB_REFS =
LIB_MCS_FLAGS = -delaysign -keyfile:../winfx.pub

include ../../build/library.make
