thisdir = class/TypeForwarders/System.Diagnostics.Tools
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.Diagnostics.Tools.dll
LIB_MCS_FLAGS = /r:System

NO_TEST = yes

include ../../../build/library.make
