//------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//------------------------------------------------------------

// NOTE: this file was generated from 'xd.xml'

namespace System.ServiceModel
{
    using System.Xml;
    using System.Runtime.CompilerServices;

    class ServiceModelStringsVersion1 : ServiceModelStrings
    {
        public const string String0 = "mustUnderstand";
        public const string String1 = "Envelope";
        public const string String2 = "http://www.w3.org/2003/05/soap-envelope";
        public const string String3 = "http://www.w3.org/2005/08/addressing";
        public const string String4 = "Header";
        public const string String5 = "Action";
        public const string String6 = "To";
        public const string String7 = "Body";
        public const string String8 = "Algorithm";
        public const string String9 = "RelatesTo";
        public const string String10 = "http://www.w3.org/2005/08/addressing/anonymous";
        public const string String11 = "URI";
        public const string String12 = "Reference";
        public const string String13 = "MessageID";
        public const string String14 = "Id";
        public const string String15 = "Identifier";
        public const string String16 = "http://schemas.xmlsoap.org/ws/2005/02/rm";
        public const string String17 = "Transforms";
        public const string String18 = "Transform";
        public const string String19 = "DigestMethod";
        public const string String20 = "DigestValue";
        public const string String21 = "Address";
        public const string String22 = "ReplyTo";
        public const string String23 = "SequenceAcknowledgement";
        public const string String24 = "AcknowledgementRange";
        public const string String25 = "Upper";
        public const string String26 = "Lower";
        public const string String27 = "BufferRemaining";
        public const string String28 = "http://schemas.microsoft.com/ws/2006/05/rm";
        public const string String29 = "http://schemas.xmlsoap.org/ws/2005/02/rm/SequenceAcknowledgement";
        public const string String30 = "SecurityTokenReference";
        public const string String31 = "Sequence";
        public const string String32 = "MessageNumber";
        public const string String33 = "http://www.w3.org/2000/09/xmldsig#";
        public const string String34 = "http://www.w3.org/2000/09/xmldsig#enveloped-signature";
        public const string String35 = "KeyInfo";
        public const string String36 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd";
        public const string String37 = "http://www.w3.org/2001/04/xmlenc#";
        public const string String38 = "http://schemas.xmlsoap.org/ws/2005/02/sc";
        public const string String39 = "DerivedKeyToken";
        public const string String40 = "Nonce";
        public const string String41 = "Signature";
        public const string String42 = "SignedInfo";
        public const string String43 = "CanonicalizationMethod";
        public const string String44 = "SignatureMethod";
        public const string String45 = "SignatureValue";
        public const string String46 = "DataReference";
        public const string String47 = "EncryptedData";
        public const string String48 = "EncryptionMethod";
        public const string String49 = "CipherData";
        public const string String50 = "CipherValue";
        public const string String51 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd";
        public const string String52 = "Security";
        public const string String53 = "Timestamp";
        public const string String54 = "Created";
        public const string String55 = "Expires";
        public const string String56 = "Length";
        public const string String57 = "ReferenceList";
        public const string String58 = "ValueType";
        public const string String59 = "Type";
        public const string String60 = "EncryptedHeader";
        public const string String61 = "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd";
        public const string String62 = "RequestSecurityTokenResponseCollection";
        public const string String63 = "http://schemas.xmlsoap.org/ws/2005/02/trust";
        public const string String64 = "http://schemas.xmlsoap.org/ws/2005/02/trust#BinarySecret";
        public const string String65 = "http://schemas.microsoft.com/ws/2006/02/transactions";
        public const string String66 = "s";
        public const string String67 = "Fault";
        public const string String68 = "MustUnderstand";
        public const string String69 = "role";
        public const string String70 = "relay";
        public const string String71 = "Code";
        public const string String72 = "Reason";
        public const string String73 = "Text";
        public const string String74 = "Node";
        public const string String75 = "Role";
        public const string String76 = "Detail";
        public const string String77 = "Value";
        public const string String78 = "Subcode";
        public const string String79 = "NotUnderstood";
        public const string String80 = "qname";
        public const string String81 = "";
        public const string String82 = "From";
        public const string String83 = "FaultTo";
        public const string String84 = "EndpointReference";
        public const string String85 = "PortType";
        public const string String86 = "ServiceName";
        public const string String87 = "PortName";
        public const string String88 = "ReferenceProperties";
        public const string String89 = "RelationshipType";
        public const string String90 = "Reply";
        public const string String91 = "a";
        public const string String92 = "http://schemas.xmlsoap.org/ws/2006/02/addressingidentity";
        public const string String93 = "Identity";
        public const string String94 = "Spn";
        public const string String95 = "Upn";
        public const string String96 = "Rsa";
        public const string String97 = "Dns";
        public const string String98 = "X509v3Certificate";
        public const string String99 = "http://www.w3.org/2005/08/addressing/fault";
        public const string String100 = "ReferenceParameters";
        public const string String101 = "IsReferenceParameter";
        public const string String102 = "http://www.w3.org/2005/08/addressing/reply";
        public const string String103 = "http://www.w3.org/2005/08/addressing/none";
        public const string String104 = "Metadata";
        public const string String105 = "http://schemas.xmlsoap.org/ws/2004/08/addressing";
        public const string String106 = "http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous";
        public const string String107 = "http://schemas.xmlsoap.org/ws/2004/08/addressing/fault";
        public const string String108 = "http://schemas.xmlsoap.org/ws/2004/06/addressingex";
        public const string String109 = "RedirectTo";
        public const string String110 = "Via";
        public const string String111 = "http://www.w3.org/2001/10/xml-exc-c14n#";
        public const string String112 = "PrefixList";
        public const string String113 = "InclusiveNamespaces";
        public const string String114 = "ec";
        public const string String115 = "SecurityContextToken";
        public const string String116 = "Generation";
        public const string String117 = "Label";
        public const string String118 = "Offset";
        public const string String119 = "Properties";
        public const string String120 = "Cookie";
        public const string String121 = "wsc";
        public const string String122 = "http://schemas.xmlsoap.org/ws/2004/04/sc";
        public const string String123 = "http://schemas.xmlsoap.org/ws/2004/04/security/sc/dk";
        public const string String124 = "http://schemas.xmlsoap.org/ws/2004/04/security/sc/sct";
        public const string String125 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/RST/SCT";
        public const string String126 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/RSTR/SCT";
        public const string String127 = "RenewNeeded";
        public const string String128 = "BadContextToken";
        public const string String129 = "c";
        public const string String130 = "http://schemas.xmlsoap.org/ws/2005/02/sc/dk";
        public const string String131 = "http://schemas.xmlsoap.org/ws/2005/02/sc/sct";
        public const string String132 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/SCT";
        public const string String133 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/SCT";
        public const string String134 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/SCT/Renew";
        public const string String135 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/SCT/Renew";
        public const string String136 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/SCT/Cancel";
        public const string String137 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/SCT/Cancel";
        public const string String138 = "http://www.w3.org/2001/04/xmlenc#aes128-cbc";
        public const string String139 = "http://www.w3.org/2001/04/xmlenc#kw-aes128";
        public const string String140 = "http://www.w3.org/2001/04/xmlenc#aes192-cbc";
        public const string String141 = "http://www.w3.org/2001/04/xmlenc#kw-aes192";
        public const string String142 = "http://www.w3.org/2001/04/xmlenc#aes256-cbc";
        public const string String143 = "http://www.w3.org/2001/04/xmlenc#kw-aes256";
        public const string String144 = "http://www.w3.org/2001/04/xmlenc#des-cbc";
        public const string String145 = "http://www.w3.org/2000/09/xmldsig#dsa-sha1";
        public const string String146 = "http://www.w3.org/2001/10/xml-exc-c14n#WithComments";
        public const string String147 = "http://www.w3.org/2000/09/xmldsig#hmac-sha1";
        public const string String148 = "http://www.w3.org/2001/04/xmldsig-more#hmac-sha256";
        public const string String149 = "http://schemas.xmlsoap.org/ws/2005/02/sc/dk/p_sha1";
        public const string String150 = "http://www.w3.org/2001/04/xmlenc#ripemd160";
        public const string String151 = "http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p";
        public const string String152 = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
        public const string String153 = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";
        public const string String154 = "http://www.w3.org/2001/04/xmlenc#rsa-1_5";
        public const string String155 = "http://www.w3.org/2000/09/xmldsig#sha1";
        public const string String156 = "http://www.w3.org/2001/04/xmlenc#sha256";
        public const string String157 = "http://www.w3.org/2001/04/xmlenc#sha512";
        public const string String158 = "http://www.w3.org/2001/04/xmlenc#tripledes-cbc";
        public const string String159 = "http://www.w3.org/2001/04/xmlenc#kw-tripledes";
        public const string String160 = "http://schemas.xmlsoap.org/2005/02/trust/tlsnego#TLS_Wrap";
        public const string String161 = "http://schemas.xmlsoap.org/2005/02/trust/spnego#GSS_Wrap";
        public const string String162 = "http://schemas.microsoft.com/ws/2006/05/security";
        public const string String163 = "dnse";
        public const string String164 = "o";
        public const string String165 = "Password";
        public const string String166 = "PasswordText";
        public const string String167 = "Username";
        public const string String168 = "UsernameToken";
        public const string String169 = "BinarySecurityToken";
        public const string String170 = "EncodingType";
        public const string String171 = "KeyIdentifier";
        public const string String172 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary";
        public const string String173 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#HexBinary";
        public const string String174 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Text";
        public const string String175 = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509SubjectKeyIdentifier";
        public const string String176 = "http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ";
        public const string String177 = "http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ1510";
        public const string String178 = "http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.0#SAMLAssertionID";
        public const string String179 = "Assertion";
        public const string String180 = "urn:oasis:names:tc:SAML:1.0:assertion";
        public const string String181 = "http://docs.oasis-open.org/wss/oasis-wss-rel-token-profile-1.0.pdf#license";
        public const string String182 = "FailedAuthentication";
        public const string String183 = "InvalidSecurityToken";
        public const string String184 = "InvalidSecurity";
        public const string String185 = "k";
        public const string String186 = "SignatureConfirmation";
        public const string String187 = "TokenType";
        public const string String188 = "http://docs.oasis-open.org/wss/oasis-wss-soap-message-security-1.1#ThumbprintSHA1";
        public const string String189 = "http://docs.oasis-open.org/wss/oasis-wss-soap-message-security-1.1#EncryptedKey";
        public const string String190 = "http://docs.oasis-open.org/wss/oasis-wss-soap-message-security-1.1#EncryptedKeySHA1";
        public const string String191 = "http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1";
        public const string String192 = "http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0";
        public const string String193 = "http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLID";
        public const string String194 = "AUTH-HASH";
        public const string String195 = "RequestSecurityTokenResponse";
        public const string String196 = "KeySize";
        public const string String197 = "RequestedTokenReference";
        public const string String198 = "AppliesTo";
        public const string String199 = "Authenticator";
        public const string String200 = "CombinedHash";
        public const string String201 = "BinaryExchange";
        public const string String202 = "Lifetime";
        public const string String203 = "RequestedSecurityToken";
        public const string String204 = "Entropy";
        public const string String205 = "RequestedProofToken";
        public const string String206 = "ComputedKey";
        public const string String207 = "RequestSecurityToken";
        public const string String208 = "RequestType";
        public const string String209 = "Context";
        public const string String210 = "BinarySecret";
        public const string String211 = "http://schemas.xmlsoap.org/ws/2005/02/trust/spnego";
        public const string String212 = " http://schemas.xmlsoap.org/ws/2005/02/trust/tlsnego";
        public const string String213 = "wst";
        public const string String214 = "http://schemas.xmlsoap.org/ws/2004/04/trust";
        public const string String215 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/RST/Issue";
        public const string String216 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/RSTR/Issue";
        public const string String217 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/Issue";
        public const string String218 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/CK/PSHA1";
        public const string String219 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/SymmetricKey";
        public const string String220 = "http://schemas.xmlsoap.org/ws/2004/04/security/trust/Nonce";
        public const string String221 = "KeyType";
        public const string String222 = "http://schemas.xmlsoap.org/ws/2004/04/trust/SymmetricKey";
        public const string String223 = "http://schemas.xmlsoap.org/ws/2004/04/trust/PublicKey";
        public const string String224 = "Claims";
        public const string String225 = "InvalidRequest";
        public const string String226 = "RequestFailed";
        public const string String227 = "SignWith";
        public const string String228 = "EncryptWith";
        public const string String229 = "EncryptionAlgorithm";
        public const string String230 = "CanonicalizationAlgorithm";
        public const string String231 = "ComputedKeyAlgorithm";
        public const string String232 = "UseKey";
        public const string String233 = "http://schemas.microsoft.com/net/2004/07/secext/WS-SPNego";
        public const string String234 = "http://schemas.microsoft.com/net/2004/07/secext/TLSNego";
        public const string String235 = "t";
        public const string String236 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue";
        public const string String237 = "http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue";
        public const string String238 = "http://schemas.xmlsoap.org/ws/2005/02/trust/Issue";
        public const string String239 = "http://schemas.xmlsoap.org/ws/2005/02/trust/SymmetricKey";
        public const string String240 = "http://schemas.xmlsoap.org/ws/2005/02/trust/CK/PSHA1";
        public const string String241 = "http://schemas.xmlsoap.org/ws/2005/02/trust/Nonce";
        public const string String242 = "RenewTarget";
        public const string String243 = "CancelTarget";
        public const string String244 = "RequestedTokenCancelled";
        public const string String245 = "RequestedAttachedReference";
        public const string String246 = "RequestedUnattachedReference";
        public const string String247 = "IssuedTokens";
        public const string String248 = "http://schemas.xmlsoap.org/ws/2005/02/trust/Renew";
        public const string String249 = "http://schemas.xmlsoap.org/ws/2005/02/trust/Cancel";
        public const string String250 = "http://schemas.xmlsoap.org/ws/2005/02/trust/PublicKey";
        public const string String251 = "Access";
        public const string String252 = "AccessDecision";
        public const string String253 = "Advice";
        public const string String254 = "AssertionID";
        public const string String255 = "AssertionIDReference";
        public const string String256 = "Attribute";
        public const string String257 = "AttributeName";
        public const string String258 = "AttributeNamespace";
        public const string String259 = "AttributeStatement";
        public const string String260 = "AttributeValue";
        public const string String261 = "Audience";
        public const string String262 = "AudienceRestrictionCondition";
        public const string String263 = "AuthenticationInstant";
        public const string String264 = "AuthenticationMethod";
        public const string String265 = "AuthenticationStatement";
        public const string String266 = "AuthorityBinding";
        public const string String267 = "AuthorityKind";
        public const string String268 = "AuthorizationDecisionStatement";
        public const string String269 = "Binding";
        public const string String270 = "Condition";
        public const string String271 = "Conditions";
        public const string String272 = "Decision";
        public const string String273 = "DoNotCacheCondition";
        public const string String274 = "Evidence";
        public const string String275 = "IssueInstant";
        public const string String276 = "Issuer";
        public const string String277 = "Location";
        public const string String278 = "MajorVersion";
        public const string String279 = "MinorVersion";
        public const string String280 = "NameIdentifier";
        public const string String281 = "Format";
        public const string String282 = "NameQualifier";
        public const string String283 = "Namespace";
        public const string String284 = "NotBefore";
        public const string String285 = "NotOnOrAfter";
        public const string String286 = "saml";
        public const string String287 = "Statement";
        public const string String288 = "Subject";
        public const string String289 = "SubjectConfirmation";
        public const string String290 = "SubjectConfirmationData";
        public const string String291 = "ConfirmationMethod";
        public const string String292 = "urn:oasis:names:tc:SAML:1.0:cm:holder-of-key";
        public const string String293 = "urn:oasis:names:tc:SAML:1.0:cm:sender-vouches";
        public const string String294 = "SubjectLocality";
        public const string String295 = "DNSAddress";
        public const string String296 = "IPAddress";
        public const string String297 = "SubjectStatement";
        public const string String298 = "urn:oasis:names:tc:SAML:1.0:am:unspecified";
        public const string String299 = "xmlns";
        public const string String300 = "Resource";
        public const string String301 = "UserName";
        public const string String302 = "urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName";
        public const string String303 = "EmailName";
        public const string String304 = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress";
        public const string String305 = "u";
        public const string String306 = "ChannelInstance";
        public const string String307 = "http://schemas.microsoft.com/ws/2005/02/duplex";
        public const string String308 = "Encoding";
        public const string String309 = "MimeType";
        public const string String310 = "CarriedKeyName";
        public const string String311 = "Recipient";
        public const string String312 = "EncryptedKey";
        public const string String313 = "KeyReference";
        public const string String314 = "e";
        public const string String315 = "http://www.w3.org/2001/04/xmlenc#Element";
        public const string String316 = "http://www.w3.org/2001/04/xmlenc#Content";
        public const string String317 = "KeyName";
        public const string String318 = "MgmtData";
        public const string String319 = "KeyValue";
        public const string String320 = "RSAKeyValue";
        public const string String321 = "Modulus";
        public const string String322 = "Exponent";
        public const string String323 = "X509Data";
        public const string String324 = "X509IssuerSerial";
        public const string String325 = "X509IssuerName";
        public const string String326 = "X509SerialNumber";
        public const string String327 = "X509Certificate";
        public const string String328 = "AckRequested";
        public const string String329 = "http://schemas.xmlsoap.org/ws/2005/02/rm/AckRequested";
        public const string String330 = "AcksTo";
        public const string String331 = "Accept";
        public const string String332 = "CreateSequence";
        public const string String333 = "http://schemas.xmlsoap.org/ws/2005/02/rm/CreateSequence";
        public const string String334 = "CreateSequenceRefused";
        public const string String335 = "CreateSequenceResponse";
        public const string String336 = "http://schemas.xmlsoap.org/ws/2005/02/rm/CreateSequenceResponse";
        public const string String337 = "FaultCode";
        public const string String338 = "InvalidAcknowledgement";
        public const string String339 = "LastMessage";
        public const string String340 = "http://schemas.xmlsoap.org/ws/2005/02/rm/LastMessage";
        public const string String341 = "LastMessageNumberExceeded";
        public const string String342 = "MessageNumberRollover";
        public const string String343 = "Nack";
        public const string String344 = "netrm";
        public const string String345 = "Offer";
        public const string String346 = "r";
        public const string String347 = "SequenceFault";
        public const string String348 = "SequenceTerminated";
        public const string String349 = "TerminateSequence";
        public const string String350 = "http://schemas.xmlsoap.org/ws/2005/02/rm/TerminateSequence";
        public const string String351 = "UnknownSequence";
        public const string String352 = "http://schemas.microsoft.com/ws/2006/02/tx/oletx";
        public const string String353 = "oletx";
        public const string String354 = "OleTxTransaction";
        public const string String355 = "PropagationToken";
        public const string String356 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor";
        public const string String357 = "wscoor";
        public const string String358 = "CreateCoordinationContext";
        public const string String359 = "CreateCoordinationContextResponse";
        public const string String360 = "CoordinationContext";
        public const string String361 = "CurrentContext";
        public const string String362 = "CoordinationType";
        public const string String363 = "RegistrationService";
        public const string String364 = "Register";
        public const string String365 = "RegisterResponse";
        public const string String366 = "ProtocolIdentifier";
        public const string String367 = "CoordinatorProtocolService";
        public const string String368 = "ParticipantProtocolService";
        public const string String369 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/CreateCoordinationContext";
        public const string String370 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/CreateCoordinationContextResponse";
        public const string String371 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/Register";
        public const string String372 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/RegisterResponse";
        public const string String373 = "http://schemas.xmlsoap.org/ws/2004/10/wscoor/fault";
        public const string String374 = "ActivationCoordinatorPortType";
        public const string String375 = "RegistrationCoordinatorPortType";
        public const string String376 = "InvalidState";
        public const string String377 = "InvalidProtocol";
        public const string String378 = "InvalidParameters";
        public const string String379 = "NoActivity";
        public const string String380 = "ContextRefused";
        public const string String381 = "AlreadyRegistered";
        public const string String382 = "http://schemas.xmlsoap.org/ws/2004/10/wsat";
        public const string String383 = "wsat";
        public const string String384 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Completion";
        public const string String385 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Durable2PC";
        public const string String386 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Volatile2PC";
        public const string String387 = "Prepare";
        public const string String388 = "Prepared";
        public const string String389 = "ReadOnly";
        public const string String390 = "Commit";
        public const string String391 = "Rollback";
        public const string String392 = "Committed";
        public const string String393 = "Aborted";
        public const string String394 = "Replay";
        public const string String395 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Commit";
        public const string String396 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Rollback";
        public const string String397 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Committed";
        public const string String398 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Aborted";
        public const string String399 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Prepare";
        public const string String400 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Prepared";
        public const string String401 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/ReadOnly";
        public const string String402 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/Replay";
        public const string String403 = "http://schemas.xmlsoap.org/ws/2004/10/wsat/fault";
        public const string String404 = "CompletionCoordinatorPortType";
        public const string String405 = "CompletionParticipantPortType";
        public const string String406 = "CoordinatorPortType";
        public const string String407 = "ParticipantPortType";
        public const string String408 = "InconsistentInternalState";
        public const string String409 = "mstx";
        public const string String410 = "Enlistment";
        public const string String411 = "protocol";
        public const string String412 = "LocalTransactionId";
        public const string String413 = "IsolationLevel";
        public const string String414 = "IsolationFlags";
        public const string String415 = "Description";
        public const string String416 = "Loopback";
        public const string String417 = "RegisterInfo";
        public const string String418 = "ContextId";
        public const string String419 = "TokenId";
        public const string String420 = "AccessDenied";
        public const string String421 = "InvalidPolicy";
        public const string String422 = "CoordinatorRegistrationFailed";
        public const string String423 = "TooManyEnlistments";
        public const string String424 = "Disabled";
        public const string String425 = "ActivityId";
        public const string String426 = "http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics";
        public const string String427 = "http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#Kerberosv5APREQSHA1";
        public const string String428 = "http://schemas.xmlsoap.org/ws/2002/12/policy";
        public const string String429 = "FloodMessage";
        public const string String430 = "LinkUtility";
        public const string String431 = "Hops";
        public const string String432 = "http://schemas.microsoft.com/net/2006/05/peer/HopCount";
        public const string String433 = "PeerVia";
        public const string String434 = "http://schemas.microsoft.com/net/2006/05/peer";
        public const string String435 = "PeerFlooder";
        public const string String436 = "PeerTo";
        public const string String437 = "http://schemas.microsoft.com/ws/2005/05/routing";
        public const string String438 = "PacketRoutable";
        public const string String439 = "http://schemas.microsoft.com/ws/2005/05/addressing/none";
        public const string String440 = "http://schemas.microsoft.com/ws/2005/05/envelope/none";
        public const string String441 = "http://www.w3.org/2001/XMLSchema-instance";
        public const string String442 = "http://www.w3.org/2001/XMLSchema";
        public const string String443 = "nil";
        public const string String444 = "type";
        public const string String445 = "char";
        public const string String446 = "boolean";
        public const string String447 = "byte";
        public const string String448 = "unsignedByte";
        public const string String449 = "short";
        public const string String450 = "unsignedShort";
        public const string String451 = "int";
        public const string String452 = "unsignedInt";
        public const string String453 = "long";
        public const string String454 = "unsignedLong";
        public const string String455 = "float";
        public const string String456 = "double";
        public const string String457 = "decimal";
        public const string String458 = "dateTime";
        public const string String459 = "string";
        public const string String460 = "base64Binary";
        public const string String461 = "anyType";
        public const string String462 = "duration";
        public const string String463 = "guid";
        public const string String464 = "anyURI";
        public const string String465 = "QName";
        public const string String466 = "time";
        public const string String467 = "date";
        public const string String468 = "hexBinary";
        public const string String469 = "gYearMonth";
        public const string String470 = "gYear";
        public const string String471 = "gMonthDay";
        public const string String472 = "gDay";
        public const string String473 = "gMonth";
        public const string String474 = "integer";
        public const string String475 = "positiveInteger";
        public const string String476 = "negativeInteger";
        public const string String477 = "nonPositiveInteger";
        public const string String478 = "nonNegativeInteger";
        public const string String479 = "normalizedString";
        public const string String480 = "ConnectionLimitReached";
        public const string String481 = "http://schemas.xmlsoap.org/soap/envelope/";
        public const string String482 = "actor";
        public const string String483 = "faultcode";
        public const string String484 = "faultstring";
        public const string String485 = "faultactor";
        public const string String486 = "detail";

        public override int Count { get { return 487; } }

        public override string this[int index]
        {
            get
            {
                DiagnosticUtility.DebugAssert(index >= 0 && index < this.Count, "check index");
                switch (index)
                {
                    case 0: return String0;
                    case 1: return String1;
                    case 2: return String2;
                    case 3: return String3;
                    case 4: return String4;
                    case 5: return String5;
                    case 6: return String6;
                    case 7: return String7;
                    case 8: return String8;
                    case 9: return String9;
                    case 10: return String10;
                    case 11: return String11;
                    case 12: return String12;
                    case 13: return String13;
                    case 14: return String14;
                    case 15: return String15;
                    case 16: return String16;
                    case 17: return String17;
                    case 18: return String18;
                    case 19: return String19;
                    case 20: return String20;
                    case 21: return String21;
                    case 22: return String22;
                    case 23: return String23;
                    case 24: return String24;
                    case 25: return String25;
                    case 26: return String26;
                    case 27: return String27;
                    case 28: return String28;
                    case 29: return String29;
                    case 30: return String30;
                    case 31: return String31;
                    case 32: return String32;
                    case 33: return String33;
                    case 34: return String34;
                    case 35: return String35;
                    case 36: return String36;
                    case 37: return String37;
                    case 38: return String38;
                    case 39: return String39;
                    case 40: return String40;
                    case 41: return String41;
                    case 42: return String42;
                    case 43: return String43;
                    case 44: return String44;
                    case 45: return String45;
                    case 46: return String46;
                    case 47: return String47;
                    case 48: return String48;
                    case 49: return String49;
                    case 50: return String50;
                    case 51: return String51;
                    case 52: return String52;
                    case 53: return String53;
                    case 54: return String54;
                    case 55: return String55;
                    case 56: return String56;
                    case 57: return String57;
                    case 58: return String58;
                    case 59: return String59;
                    case 60: return String60;
                    case 61: return String61;
                    case 62: return String62;
                    case 63: return String63;
                    case 64: return String64;
                    case 65: return String65;
                    case 66: return String66;
                    case 67: return String67;
                    case 68: return String68;
                    case 69: return String69;
                    case 70: return String70;
                    case 71: return String71;
                    case 72: return String72;
                    case 73: return String73;
                    case 74: return String74;
                    case 75: return String75;
                    case 76: return String76;
                    case 77: return String77;
                    case 78: return String78;
                    case 79: return String79;
                    case 80: return String80;
                    case 81: return String81;
                    case 82: return String82;
                    case 83: return String83;
                    case 84: return String84;
                    case 85: return String85;
                    case 86: return String86;
                    case 87: return String87;
                    case 88: return String88;
                    case 89: return String89;
                    case 90: return String90;
                    case 91: return String91;
                    case 92: return String92;
                    case 93: return String93;
                    case 94: return String94;
                    case 95: return String95;
                    case 96: return String96;
                    case 97: return String97;
                    case 98: return String98;
                    case 99: return String99;
                    case 100: return String100;
                    case 101: return String101;
                    case 102: return String102;
                    case 103: return String103;
                    case 104: return String104;
                    case 105: return String105;
                    case 106: return String106;
                    case 107: return String107;
                    case 108: return String108;
                    case 109: return String109;
                    case 110: return String110;
                    case 111: return String111;
                    case 112: return String112;
                    case 113: return String113;
                    case 114: return String114;
                    case 115: return String115;
                    case 116: return String116;
                    case 117: return String117;
                    case 118: return String118;
                    case 119: return String119;
                    case 120: return String120;
                    case 121: return String121;
                    case 122: return String122;
                    case 123: return String123;
                    case 124: return String124;
                    case 125: return String125;
                    case 126: return String126;
                    case 127: return String127;
                    case 128: return String128;
                    case 129: return String129;
                    case 130: return String130;
                    case 131: return String131;
                    case 132: return String132;
                    case 133: return String133;
                    case 134: return String134;
                    case 135: return String135;
                    case 136: return String136;
                    case 137: return String137;
                    case 138: return String138;
                    case 139: return String139;
                    case 140: return String140;
                    case 141: return String141;
                    case 142: return String142;
                    case 143: return String143;
                    case 144: return String144;
                    case 145: return String145;
                    case 146: return String146;
                    case 147: return String147;
                    case 148: return String148;
                    case 149: return String149;
                    case 150: return String150;
                    case 151: return String151;
                    case 152: return String152;
                    case 153: return String153;
                    case 154: return String154;
                    case 155: return String155;
                    case 156: return String156;
                    case 157: return String157;
                    case 158: return String158;
                    case 159: return String159;
                    case 160: return String160;
                    case 161: return String161;
                    case 162: return String162;
                    case 163: return String163;
                    case 164: return String164;
                    case 165: return String165;
                    case 166: return String166;
                    case 167: return String167;
                    case 168: return String168;
                    case 169: return String169;
                    case 170: return String170;
                    case 171: return String171;
                    case 172: return String172;
                    case 173: return String173;
                    case 174: return String174;
                    case 175: return String175;
                    case 176: return String176;
                    case 177: return String177;
                    case 178: return String178;
                    case 179: return String179;
                    case 180: return String180;
                    case 181: return String181;
                    case 182: return String182;
                    case 183: return String183;
                    case 184: return String184;
                    case 185: return String185;
                    case 186: return String186;
                    case 187: return String187;
                    case 188: return String188;
                    case 189: return String189;
                    case 190: return String190;
                    case 191: return String191;
                    case 192: return String192;
                    case 193: return String193;
                    case 194: return String194;
                    case 195: return String195;
                    case 196: return String196;
                    case 197: return String197;
                    case 198: return String198;
                    case 199: return String199;
                    case 200: return String200;
                    case 201: return String201;
                    case 202: return String202;
                    case 203: return String203;
                    case 204: return String204;
                    case 205: return String205;
                    case 206: return String206;
                    case 207: return String207;
                    case 208: return String208;
                    case 209: return String209;
                    case 210: return String210;
                    case 211: return String211;
                    case 212: return String212;
                    case 213: return String213;
                    case 214: return String214;
                    case 215: return String215;
                    case 216: return String216;
                    case 217: return String217;
                    case 218: return String218;
                    case 219: return String219;
                    case 220: return String220;
                    case 221: return String221;
                    case 222: return String222;
                    case 223: return String223;
                    case 224: return String224;
                    case 225: return String225;
                    case 226: return String226;
                    case 227: return String227;
                    case 228: return String228;
                    case 229: return String229;
                    case 230: return String230;
                    case 231: return String231;
                    case 232: return String232;
                    case 233: return String233;
                    case 234: return String234;
                    case 235: return String235;
                    case 236: return String236;
                    case 237: return String237;
                    case 238: return String238;
                    case 239: return String239;
                    case 240: return String240;
                    case 241: return String241;
                    case 242: return String242;
                    case 243: return String243;
                    case 244: return String244;
                    case 245: return String245;
                    case 246: return String246;
                    case 247: return String247;
                    case 248: return String248;
                    case 249: return String249;
                    case 250: return String250;
                    case 251: return String251;
                    case 252: return String252;
                    case 253: return String253;
                    case 254: return String254;
                    case 255: return String255;
                    case 256: return String256;
                    case 257: return String257;
                    case 258: return String258;
                    case 259: return String259;
                    case 260: return String260;
                    case 261: return String261;
                    case 262: return String262;
                    case 263: return String263;
                    case 264: return String264;
                    case 265: return String265;
                    case 266: return String266;
                    case 267: return String267;
                    case 268: return String268;
                    case 269: return String269;
                    case 270: return String270;
                    case 271: return String271;
                    case 272: return String272;
                    case 273: return String273;
                    case 274: return String274;
                    case 275: return String275;
                    case 276: return String276;
                    case 277: return String277;
                    case 278: return String278;
                    case 279: return String279;
                    case 280: return String280;
                    case 281: return String281;
                    case 282: return String282;
                    case 283: return String283;
                    case 284: return String284;
                    case 285: return String285;
                    case 286: return String286;
                    case 287: return String287;
                    case 288: return String288;
                    case 289: return String289;
                    case 290: return String290;
                    case 291: return String291;
                    case 292: return String292;
                    case 293: return String293;
                    case 294: return String294;
                    case 295: return String295;
                    case 296: return String296;
                    case 297: return String297;
                    case 298: return String298;
                    case 299: return String299;
                    case 300: return String300;
                    case 301: return String301;
                    case 302: return String302;
                    case 303: return String303;
                    case 304: return String304;
                    case 305: return String305;
                    case 306: return String306;
                    case 307: return String307;
                    case 308: return String308;
                    case 309: return String309;
                    case 310: return String310;
                    case 311: return String311;
                    case 312: return String312;
                    case 313: return String313;
                    case 314: return String314;
                    case 315: return String315;
                    case 316: return String316;
                    case 317: return String317;
                    case 318: return String318;
                    case 319: return String319;
                    case 320: return String320;
                    case 321: return String321;
                    case 322: return String322;
                    case 323: return String323;
                    case 324: return String324;
                    case 325: return String325;
                    case 326: return String326;
                    case 327: return String327;
                    case 328: return String328;
                    case 329: return String329;
                    case 330: return String330;
                    case 331: return String331;
                    case 332: return String332;
                    case 333: return String333;
                    case 334: return String334;
                    case 335: return String335;
                    case 336: return String336;
                    case 337: return String337;
                    case 338: return String338;
                    case 339: return String339;
                    case 340: return String340;
                    case 341: return String341;
                    case 342: return String342;
                    case 343: return String343;
                    case 344: return String344;
                    case 345: return String345;
                    case 346: return String346;
                    case 347: return String347;
                    case 348: return String348;
                    case 349: return String349;
                    case 350: return String350;
                    case 351: return String351;
                    case 352: return String352;
                    case 353: return String353;
                    case 354: return String354;
                    case 355: return String355;
                    case 356: return String356;
                    case 357: return String357;
                    case 358: return String358;
                    case 359: return String359;
                    case 360: return String360;
                    case 361: return String361;
                    case 362: return String362;
                    case 363: return String363;
                    case 364: return String364;
                    case 365: return String365;
                    case 366: return String366;
                    case 367: return String367;
                    case 368: return String368;
                    case 369: return String369;
                    case 370: return String370;
                    case 371: return String371;
                    case 372: return String372;
                    case 373: return String373;
                    case 374: return String374;
                    case 375: return String375;
                    case 376: return String376;
                    case 377: return String377;
                    case 378: return String378;
                    case 379: return String379;
                    case 380: return String380;
                    case 381: return String381;
                    case 382: return String382;
                    case 383: return String383;
                    case 384: return String384;
                    case 385: return String385;
                    case 386: return String386;
                    case 387: return String387;
                    case 388: return String388;
                    case 389: return String389;
                    case 390: return String390;
                    case 391: return String391;
                    case 392: return String392;
                    case 393: return String393;
                    case 394: return String394;
                    case 395: return String395;
                    case 396: return String396;
                    case 397: return String397;
                    case 398: return String398;
                    case 399: return String399;
                    case 400: return String400;
                    case 401: return String401;
                    case 402: return String402;
                    case 403: return String403;
                    case 404: return String404;
                    case 405: return String405;
                    case 406: return String406;
                    case 407: return String407;
                    case 408: return String408;
                    case 409: return String409;
                    case 410: return String410;
                    case 411: return String411;
                    case 412: return String412;
                    case 413: return String413;
                    case 414: return String414;
                    case 415: return String415;
                    case 416: return String416;
                    case 417: return String417;
                    case 418: return String418;
                    case 419: return String419;
                    case 420: return String420;
                    case 421: return String421;
                    case 422: return String422;
                    case 423: return String423;
                    case 424: return String424;
                    case 425: return String425;
                    case 426: return String426;
                    case 427: return String427;
                    case 428: return String428;
                    case 429: return String429;
                    case 430: return String430;
                    case 431: return String431;
                    case 432: return String432;
                    case 433: return String433;
                    case 434: return String434;
                    case 435: return String435;
                    case 436: return String436;
                    case 437: return String437;
                    case 438: return String438;
                    case 439: return String439;
                    case 440: return String440;
                    case 441: return String441;
                    case 442: return String442;
                    case 443: return String443;
                    case 444: return String444;
                    case 445: return String445;
                    case 446: return String446;
                    case 447: return String447;
                    case 448: return String448;
                    case 449: return String449;
                    case 450: return String450;
                    case 451: return String451;
                    case 452: return String452;
                    case 453: return String453;
                    case 454: return String454;
                    case 455: return String455;
                    case 456: return String456;
                    case 457: return String457;
                    case 458: return String458;
                    case 459: return String459;
                    case 460: return String460;
                    case 461: return String461;
                    case 462: return String462;
                    case 463: return String463;
                    case 464: return String464;
                    case 465: return String465;
                    case 466: return String466;
                    case 467: return String467;
                    case 468: return String468;
                    case 469: return String469;
                    case 470: return String470;
                    case 471: return String471;
                    case 472: return String472;
                    case 473: return String473;
                    case 474: return String474;
                    case 475: return String475;
                    case 476: return String476;
                    case 477: return String477;
                    case 478: return String478;
                    case 479: return String479;
                    case 480: return String480;
                    case 481: return String481;
                    case 482: return String482;
                    case 483: return String483;
                    case 484: return String484;
                    case 485: return String485;
                    case 486: return String486;
                    default: return null;
                }
            }
        }
    }
}
