thisdir = class/I18N/Rare
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = I18N.Rare.dll
LIB_REFS = I18N
KEYFILE = ../../mono.pub
LOCAL_MCS_FLAGS = /unsafe
TEST_LIB_REFS = I18N

EXTRA_DISTFILES = $(wildcard *.ucm)

include ../../../build/library.make
