thisdir = class/System.Configuration.Install
include ../../build/rules.make

LIBRARY = System.Configuration.Install.dll
LIB_REFS = System System.Xml
LIB_MCS_FLAGS = /r:$(corlib)

NO_TEST = yes

include ../../build/library.make
