thisdir = class/RabbitMQ.Client
#SUBDIRS = src/bootstrap src/apigen docs/specs src/client
SUBDIRS = docs/specs src/client
include ../../build/rules.make

all-local install-local clean-local test-local run-test-local run-test-ondotnet-local uninstall-local doc-update-local:

dist-local: dist-default
