thisdir = class/System.Json
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Json.dll
LIB_REFS = System System.Xml System.Core
LIB_MCS_FLAGS =

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

EXTRA_DISTFILES =

include ../../build/library.make
