thisdir = class/System.Web.Extensions/Test
include ../../../build/rules.make

all-local install-local clean-local test-local run-test-local run-test-ondotnet-local uninstall-local:

DISTFILES =  $(wildcard *.aspx)

dist-local: dist-default
