thisdir = class/TypeForwarders/System.ServiceModel.Security
SUBDIRS = 
include ../../../build/rules.make

LIBRARY = System.ServiceModel.Security.dll
LIB_MCS_FLAGS = /r:System.ServiceModel

NO_TEST = yes

include ../../../build/library.make
