thisdir = tools/corcompare
SUBDIRS =
include ../../build/rules.make

LIB_REFS = Mono.Cecil System.Xml System.Core System
LOCAL_MCS_FLAGS =

PROGRAM = mono-api-info.exe

include ../../build/executable.make
