<?xml version="1.0" encoding="utf-8"?>
<Database Name="Northwind" EntityNamespace="MsNorthwind" ContextNamespace="MsNorthwind" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=GEUS-LAPTOP\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=True" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Category_Product" Member="Products" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" OtherKey="CustomerID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TitleOfCourtesy" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ReportsTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Employee" Member="Employees" OtherKey="ReportsTo" Type="Employee" />
      <Association Name="Employee_EmployeeTerritory" Member="EmployeeTerritories" OtherKey="EmployeeID" Type="EmployeeTerritory" />
      <Association Name="Employee_Order" Member="Orders" OtherKey="EmployeeID" Type="Order" />
      <Association Name="Employee_Employee" Member="ReportsToEmployee" ThisKey="ReportsTo" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order Details]" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTerritories" Member="EmployeeTerritories">
    <Type Name="EmployeeTerritory">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Employee_EmployeeTerritory" Member="Employee" ThisKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Territory_EmployeeTerritory" Member="Territory" ThisKey="TerritoryID" Type="Territory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" OtherKey="OrderID" Type="OrderDetail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Shipper_Order" Member="Shipper" ThisKey="ShipVia" Type="Shipper" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityPerUnit" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UnitsOnOrder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReorderLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Discontinued" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="Supplier_Product" Member="Supplier" ThisKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Region" Member="Regions">
    <Type Name="Region">
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegionDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Region_Territory" Member="Territories" OtherKey="RegionID" Type="Territory" />
    </Type>
  </Table>
  <Table Name="dbo.Shippers" Member="Shippers">
    <Type Name="Shipper">
      <Column Name="ShipperID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Association Name="Shipper_Order" Member="Orders" OtherKey="ShipVia" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Association Name="Supplier_Product" Member="Products" OtherKey="SupplierID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Territories" Member="Territories">
    <Type Name="Territory">
      <Column Name="TerritoryID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Territory_EmployeeTerritory" Member="EmployeeTerritories" OtherKey="TerritoryID" Type="EmployeeTerritory" />
      <Association Name="Region_Territory" Member="Region" ThisKey="RegionID" Type="Region" IsForeignKey="true" />
    </Type>
  </Table>
</Database>