DROP DATABASE "GHTDB";
CREATE DATABASE "GHTDB"
  WITH OWNER = postgres
       ENCODING = 'UNICODE'
       TABLESPACE = pg_default;

DROP DATABASE "GHTDBEX";
CREATE DATABASE "GHTDBEX"
  WITH OWNER = postgres
       ENCODING = 'UNICODE'
       TABLESPACE = pg_default;
