/*
 * mono-threads-coop.h: Cooperative suspend thread helpers
 *
 * Author:
 *	Rodrigo Kumpera (kumpera@gmail.com)
 *
 * (C) 2015 Xamarin
 */

#ifndef __MONO_THREADS_COOP_H__
#define __MONO_THREADS_COOP_H__

#include <config.h>

#ifdef USE_COOP_GC

#define MONO_SUSPEND_CHECK MONO_SUSPEND_CHECK_FORCED
#define MONO_PREPARE_BLOCKING MONO_PREPARE_BLOCKING_FORCED
#define MONO_FINISH_BLOCKING MONO_FINISH_BLOCKING_FORCED
#define MONO_PREPARE_RESET_BLOCKING MONO_PREPARE_RESET_BLOCKING_FORCED
#define MONO_FINISH_RESET_BLOCKING MONO_FINISH_RESET_BLOCKING_FORCED
#define MONO_TRY_BLOCKING MONO_TRY_BLOCKING_FORCED
#define MONO_FINISH_TRY_BLOCKING MONO_FINISH_TRY_BLOCKING_FORCED
}

#else

#define MONO_SUSPEND_CHECK do {	} while (0);
#define MONO_PREPARE_BLOCKING {
#define MONO_FINISH_BLOCKING }
#define MONO_PREPARE_RESET_BLOCKING {
#define MONO_FINISH_RESET_BLOCKING }
#define MONO_TRY_BLOCKING {
#define MONO_FINISH_TRY_BLOCKING }

#endif /* USE_COOP_GC */


#endif
